project:
  type: website

website:
  title: "Minh Dang"
  navbar:
    background: "#ff9600"
    foreground: "#000000"
    pinned: true
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/minhdang241
      - icon: linkedin
        href: https://www.linkedin.com/in/minh-dang-60406b17b/
  comments:
    utterances:
      repo: minhdang241/minhdang241.github.io
format:
  html:
    theme: cosmo
    css: styles.css
